// Cleaned mock book data compatible with Product schema
const allbooks = {
  fiction: [
    { title: "The Midnight Garden", author: "Sarah Mitchell", description: "A magical tale of hidden worlds and unexpected friendships.", price: 599, originalPrice: 699, rating: 4.8, reviews: 156, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=The+Midnight+Garden", alt: "The Midnight Garden", isPrimary: true }], isNew: true, isFeatured: true, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Chronicles of Tomorrow", author: "Michael Chen", description: "A futuristic adventure exploring technology and destiny.", price: 450, rating: 4.6, reviews: 89, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Chronicles+of+Tomorrow", alt: "Chronicles of Tomorrow", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Whispers in the Dark", author: "Emma Johnson", description: "A suspenseful thriller full of secrets and twists.", price: 375, rating: 4.9, reviews: 234, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Whispers+in+the+Dark", alt: "Whispers in the Dark", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "The Lost Symphony", author: "David Rodriguez", description: "A story of love, loss, and music that transcends time.", price: 525, rating: 4.4, reviews: 67, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=The+Lost+Symphony", alt: "The Lost Symphony", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Beyond the Horizon", author: "Lisa Park", description: "A journey across seas and dreams, chasing freedom.", price: 425, rating: 4.7, reviews: 145, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Beyond+the+Horizon", alt: "Beyond the Horizon", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Echoes of Yesterday", author: "James Wilson", description: "An emotional tale of memories, regrets, and hope.", price: 350, originalPrice: 400, rating: 4.5, reviews: 78, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Echoes+of+Yesterday", alt: "Echoes of Yesterday", isPrimary: true }], isNew: false, isFeatured: false, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Whispers in the Wind", author: "Emma Carter", description: "A heartfelt novel about love, change, and letting go.", price: 280, rating: 4.2, reviews: 56, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Whispers+in+the+Wind", alt: "Whispers in the Wind", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "The Forgotten Path", author: "Daniel Harris", description: "A mysterious road leads to self-discovery and destiny.", price: 400, rating: 4.7, reviews: 112, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=The+Forgotten+Path", alt: "The Forgotten Path", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Whispers of the Night", author: "Emma Carter", description: "Chilling stories told in the silence of the night.", price: 320, rating: 4.2, reviews: 56, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Whispers+of+the+Night", alt: "Whispers of the Night", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Dancing with Dreams", author: "Isabella Brown", description: "A romantic story about dreams, love, and ambitions.", price: 280, rating: 4.0, reviews: 40, category: "fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Dancing+with+Dreams", alt: "Dancing with Dreams", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
  ],

  "non-fiction": [
    { title: "The Science of Success", author: "Dr. Amanda Foster", description: "An inspiring guide on habits and mindset for achieving greatness.", price: 675, rating: 4.9, reviews: 289, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=The+Science+of+Success", alt: "The Science of Success", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Mindful Leadership", author: "Robert Kumar", description: "Practical steps to lead with mindfulness and empathy.", price: 550, rating: 4.6, reviews: 134, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Mindful+Leadership", alt: "Mindful Leadership", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "History Reimagined", author: "Dr. Olivia Bennett", description: "Exploring historical events from a fresh perspective.", price: 600, rating: 4.5, reviews: 98, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=History+Reimagined", alt: "History Reimagined", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "The Art of Productivity", author: "Samuel Lee", description: "Learn how to maximize your output without burnout.", price: 450, rating: 4.4, reviews: 75, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=The+Art+of+Productivity", alt: "The Art of Productivity", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Innovation Mindset", author: "Carla Diaz", description: "Unlock creativity and foster innovation in business.", price: 500, rating: 4.7, reviews: 120, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Innovation+Mindset", alt: "Innovation Mindset", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Thinking Clearly", author: "Victor Chen", description: "Improve decision-making and clarity of thought.", price: 400, rating: 4.3, reviews: 95, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Thinking+Clearly", alt: "Thinking Clearly", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "The Leadership Code", author: "Nancy Wright", description: "Core principles of effective leadership.", price: 550, rating: 4.6, reviews: 140, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=The+Leadership+Code", alt: "The Leadership Code", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Understanding Economics", author: "Dr. Robert Kim", description: "A beginner-friendly guide to economics.", price: 620, rating: 4.5, reviews: 160, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Understanding+Economics", alt: "Understanding Economics", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Psychology of Habits", author: "Anna White", description: "Discover the science behind habits and how to change them.", price: 480, rating: 4.4, reviews: 110, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Psychology+of+Habits", alt: "Psychology of Habits", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Global Perspectives", author: "Liam Scott", description: "Insights into global issues and solutions.", price: 530, rating: 4.6, reviews: 132, category: "non-fiction", images: [{ url: "https://via.placeholder.com/200x300?text=Global+Perspectives", alt: "Global Perspectives", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
  ],

  education: [
    { title: "Advanced Mathematics", author: "Prof. Sarah Williams", description: "Comprehensive guide covering advanced mathematical concepts.", price: 850, rating: 4.7, reviews: 203, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Advanced+Mathematics", alt: "Advanced Mathematics", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Computer Science Fundamentals", author: "Dr. Raj Patel", description: "An introduction to the building blocks of computer science.", price: 725, rating: 4.8, reviews: 178, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Computer+Science+Fundamentals", alt: "Computer Science Fundamentals", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Physics for Engineers", author: "Dr. John Doe", description: "Detailed explanation of physics concepts for engineers.", price: 650, rating: 4.6, reviews: 145, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Physics+for+Engineers", alt: "Physics for Engineers", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Chemistry Essentials", author: "Dr. Jane Smith", description: "Fundamental chemistry concepts explained simply.", price: 600, rating: 4.5, reviews: 120, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Chemistry+Essentials", alt: "Chemistry Essentials", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Biology Basics", author: "Dr. Alice Brown", description: "Explore the fundamentals of biology.", price: 580, rating: 4.4, reviews: 110, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Biology+Basics", alt: "Biology Basics", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Data Structures in Depth", author: "Prof. Michael Lee", description: "Detailed guide on data structures for programmers.", price: 750, rating: 4.7, reviews: 190, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Data+Structures+in+Depth", alt: "Data Structures in Depth", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Algorithms Unlocked", author: "Dr. Laura Wilson", description: "Step-by-step explanation of core algorithms.", price: 800, rating: 4.8, reviews: 210, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Algorithms+Unlocked", alt: "Algorithms Unlocked", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Linear Algebra Mastery", author: "Prof. Robert King", description: "Master linear algebra with practical examples.", price: 700, rating: 4.6, reviews: 170, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Linear+Algebra+Mastery", alt: "Linear Algebra Mastery", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: false, stock: 10, seller: "000000000000000000000000" },
    { title: "Probability & Statistics", author: "Dr. Emily Clark", description: "Learn probability and statistics for real-world use.", price: 680, rating: 4.5, reviews: 160, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Probability+%26+Statistics", alt: "Probability & Statistics", isPrimary: true }], isNew: false, isFeatured: true, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
    { title: "Machine Learning Basics", author: "Dr. Kevin Harris", description: "Introduction to machine learning and AI basics.", price: 900, rating: 4.9, reviews: 240, category: "education", images: [{ url: "https://via.placeholder.com/200x300?text=Machine+Learning+Basics", alt: "Machine Learning Basics", isPrimary: true }], isNew: true, isFeatured: false, isBestSeller: true, stock: 10, seller: "000000000000000000000000" },
  ]
};

module.exports = allbooks;
